### PR TITLE
adds a placeholder image to the item

### PR DESCRIPTION
**Pull request by joshmkennedy**
# Description

If there was no image given when creating a product then a placeholder image will be displayed instead.

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks @joshmkennedy, I'll review the changes right away!

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Comment by joshmkennedy** [comment]
Screen Shot 2022-07-26 at 10 18 12 AM

**Review by vanessa-cooper — APPROVED** [review]
Excellent job @joshmkennedy! You're now able to merge the PR.

**Pull request merged**
